### ISSUE TITLE
Share Link to Article missing CSS

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#100]
The Share Link to Article is missing CSS for the button, and when expanded is missing the layout that shows the full article in a box below the button. You can see this in the article http://outdev2.1to1vpn.ddns.net:9015/f/customerportal-treeview#/find-answers?topicID=16&articleID=111. 

Instead of the below:
![sharelink](https://cloud.githubusercontent.com/assets/16782471/15790811/27236c30-2999-11e6-998d-bcc2322b2cf2.png)

It should look like this:
![sharelinkok](https://cloud.githubusercontent.com/assets/16782471/15790813/2ade9a02-2999-11e6-9dfe-9e588f722c68.png)

It appears that the required CSS is within the Header form. The portal must work properly without the header or footer forms because those will be different for every customer using the form.

**Comment by jaswantchouhan** [comment]
fixed the issue, please provide the git hub location or place to commit the added code.

**Comment by scottwhitsitt** [comment]
JC - this needs to be corrected in 7.4. Please confirm the location for testing this. The Outdev2 site is version 7.5, so if you made the changes there they need to be ported over to QA.iServiceCRM.

**Comment by jaswantchouhan** [comment]
I have corrected it on 7.4 added a new form customerportal-treeview-head
form-id 121 in https://qa.iservicecrm.com , you can test it on
https://qa.iservicecrm.com/f/112#/find-answers, please confirm the git
location to commit the changes.

**Comment by swhitsit** [comment]
tested OK on form 112

**Comment by sdubrick** [comment]
Please keep this inside the main form

**Comment by jaswantchouhan** [comment]
issue #100 - same has been fixed please check on
https://qa.iservicecrm.com/f/122#/find-answers

**Comment by scottwhitsitt** [comment]
This is confirmed fixed in form 122
