### ISSUE TITLE
Get This button needs to be removed

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#101]
The Get This button is displaying in the customer history. This is an agent button, and should never be shown to customers. Also, it is not functional until 7.5.

![2016-06-08_11-24-31](https://cloud.githubusercontent.com/assets/16782471/15902120/fea80230-2d6b-11e6-9f94-02b4a85cabaf.png)

**Comment by scottwhitsitt** [comment]
I think this is not an issue with the form, but configuration of the QA.iServiceCRM websites to use in process history partials coding.

**Comment by jaswantchouhan** [comment]
issue #101 - i have fixed it using the ng-template from diag-builtinforms
form script you can check it https://qa.iservicecrm.com/f/122#/find-answers
is this correct ?

**Comment by scottwhitsitt** [comment]
This was a config issue with the website, not the support portal form.
