### ISSUE TITLE
Views not sorted properly

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#102]
As shown below, the view column is treating the value as text instead of numeric.

![2016-06-08_11-53-39](https://cloud.githubusercontent.com/assets/16782471/15902884/ca23aa60-2d6f-11e6-96ab-3bf3c4341a07.png)

**Comment by jaswantchouhan** [comment]
issue #102 - same has been fixed please check on
https://qa.iservicecrm.com/f/122#/find-answers

**Comment by scottwhitsitt** [comment]
This is confirmed fixed in form 122
