### ISSUE TITLE
Change Top FAQ to Top FAQs

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#103]
![2016-06-08_11-56-08](https://cloud.githubusercontent.com/assets/16782471/15902974/1c99199c-2d70-11e6-8de6-6c2699f4c3d8.png)

**Comment by jaswantchouhan** [comment]
issue #103 -  same has been fixed please check on
https://qa.iservicecrm.com/f/122#/find-answers

**Comment by scottwhitsitt** [comment]
This is confirmed fixed in form 122
