### ISSUE TITLE
Move any treeview specific css/js out of 1to1header.frm and into the Treeview form

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#105]
There seems to be some code specific to the Treeview form which is still in the 1to1header.frm form.  For example, hovering over this button
![image](https://cloud.githubusercontent.com/assets/5289502/15973509/7a5fd076-2f09-11e6-8236-49fd63884fee.png)
causes it to change purple if the header is pointing to our 1to1header in placeholders.  Without this, it does not change color.
Please review the 1to1header.frm and be sure to take out anything that is specific to TreeView form, and then put it into the treeview form instead..

**Comment by jaswantchouhan** [comment]
#105 - Not able to reproduce

**Comment by sdubrick** [comment]
https://qa.iservicecrm.com/f/customerportal-treeview#/find-answers
Click on any article, hover over share link.  It doesn't turn purple.

It's because you have css that it relies on inside the wrong form.  You need to move the stuff that's in the 1to1header out and into the treeview form.  There might be other css code too.  This is just one example.

**Comment by jaswantchouhan** [comment]
#105 fixed - http://outdev2.1to1vpn.ddns.net:9015/f/58

**Comment by scottwhitsitt** [comment]
Tested ok on outdev2

**Comment by sdubrick** [comment]
@jaswantchouhan please link to the new 1to1header.frm also with your changes and i'll check in your changes for that too

**Comment by jaswantchouhan** [comment]
Updated 1to1header and 1to1footer for css and html guideline http://outdev2.1to1vpn.ddns.net:9015/f/59
http://outdev2.1to1vpn.ddns.net:9015/f/60

**Comment by sdubrick** [comment]
Did a quick test with and without header/footer placeholders pointing to 59/60, and seems to be ok
