### ISSUE TITLE
Include All Sub-Topics topic count not working

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#109]
The checkbox for Include All is not updating the article count. When unchecked, it still shows the total for all of the articles in child topics.

![2016-06-22_11-53-23](https://cloud.githubusercontent.com/assets/16782471/16275557/1ff5ea42-3870-11e6-83dd-570d70ce1e5d.png)

**Comment by jaswantchouhan** [comment]
Issue #109 -  has been fixed please verify the topic count update on http://outdev2.1to1vpn.ddns.net:9015/f/58#/find-answers

**Comment by sdubrick** [comment]
#112

**Comment by sdubrick** [comment]
@jaswantchouhan you need to submit the changes in pull request
@scottwhitsitt this needs to be verified

**Comment by scottwhitsitt** [comment]
Confirmed that the counts and article lists update properly when sub topics are included / excluded.

**Comment by sdubrick** [comment]
@jaswantchouhan please add to your pull request (and tag this issue in it)
