### ISSUE TITLE
Form Admin page sorting resets

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#110]
Selecting a form resets any custom sorting on the form admin page.  This should be fixed so that sorting doesn't reset

**Comment by scottwhitsitt** [comment]
@ashrafsabrym This is a built in form. We'd like you to try and correct this issue related to losing the sort position on form selection. I think the actual form is http://outdev1.1to1vpn.ddns.net:9015/admin#/formbuiltin/ngappbuiltin-admin-form. You would need to make a copy of this form to make your edits.

**Comment by ashrafsabrym** [comment]
Fixed in PR #119 on outdev1. Please verify.
Only modified file iService.admin.js

**Comment by sdubrick** [comment]
Tenant was upgraded and js wiped, but I put your iService.admin.js back in.

**Comment by sdubrick** [comment]
Looks good to me, closing and adding to dragnet
