### ISSUE TITLE
Top level topic does not highlight correctly

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#111]
Subtopics highlight correctly when they are active:
![image](https://cloud.githubusercontent.com/assets/5289502/16661767/23428040-443a-11e6-928b-fca417cad6c0.png)

However, the top level topic does not:
![image](https://cloud.githubusercontent.com/assets/5289502/16661808/5fa0dfbe-443a-11e6-9f8b-b0a5dcaa16c0.png)

please fix

**Comment by sdubrick** [comment]
#112

**Comment by jaswantchouhan** [comment]
issue - #111 topic highlighting is fixed - you can verify it on http://outdev2.1to1vpn.ddns.net:9015/f/58#/find-answers

**Comment by scottwhitsitt** [comment]
Verified this is working on 7/12/2016

**Comment by scottwhitsitt** [comment]
Tested and working on outdev2 on 7/12/2016

**Comment by sdubrick** [comment]
@jaswantchouhan please add to your pull request (and tag this issue in it)
