### ISSUE TITLE
Login not functioning in portal code

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#114]
#112 2

The login button does not log the user into iService.

**Comment by scottwhitsitt** [comment]
Login works on http://outdev2.1to1vpn.ddns.net:9015/Form.aspx?formID=58#/find-answers

Most likely this was fixed in 590850a

**Comment by jaswantchouhan** [comment]
Hi Scott- is issue still persist. i am not able to reproduce login issue

**Comment by scottwhitsitt** [comment]
Fixed now in the built in version 7/12/2016. No code commit needed.
