### ISSUE TITLE
Images pasted into CKeditor and saved do not display correctly inside CKeditor on reload

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#118]
If and image is pasted into a response (MyQueue page) and the message is then Saved, the saved version doesn't display correctly in CKeditor. Note that the image actually correctly displays if the message is send via email, or if the interaction is opened in the old CLeditor instead. The bug here appears to just be in how CKeditor is trying to display the saved image. See repro at http://screencast.com/t/BfHlLWfVlYm

The issue is that the & is converted inside CKEditor to the below.
<img alt="" src="File.aspx?interactionID=25383&amp;fileID=15" />

The "amp;" text needs to be removed.

![ckeditor](https://cloud.githubusercontent.com/assets/16782471/16775968/b9956336-4828-11e6-8cd0-e098741eb648.png)

**Comment by ashrafsabrym** [comment]
In attempt to fix the issue, I postponed setting the CKEditor markup by 100 milliseconds after a message is saved. The issue doesn't occur now, but we have to know its cause and fix it.

**Comment by scottwhitsitt** [comment]
This is an improvement and we should go with it. @sdubrick please coordinate the code with Adam.
