### ISSUE TITLE
Agent Message List should appear directly under the selected agent 

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#12]
Something like this cheap mockup:

![image](https://cloud.githubusercontent.com/assets/5289502/12659957/02a29fe6-c5d7-11e5-8c83-c3704706b016.png)

**Comment by ashrafsabrym** [comment]
Fixed in PR #20

**Comment by ashrafsabrym** [comment]
I styled the cell in which messages details are displayed to make it distinguishable. I gave it padding and dashed border.

This style may be easily modified by modifying the `.common-search-results .agent-messages` CSS rule.
