### ISSUE TITLE
Create a cancel image for button use

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#121]
We need a button with the exact height as the other buttons you've made (the new Send, Forward, etc.) for the cancel action. The actions panel is currently making the button via css, and since it's not an image like the other it is causing a display issue. If you convert this into a button it should make the wrapping of buttons align properly.

The button is below:
![cancel](https://cloud.githubusercontent.com/assets/16782471/17084994/84ef8c7e-5192-11e6-8b9d-7e7dd94bed40.jpg)

The wrapping issue is as follows:
![cancel2](https://cloud.githubusercontent.com/assets/16782471/17084997/bbfe00f6-5192-11e6-847e-7b04855b1881.jpg)

**Comment by jaswantchouhan** [comment]
please find attached button
![cancel](https://cloud.githubusercontent.com/assets/16934586/17098190/b88eb216-527e-11e6-93b5-b7567d563cf2.png)
![cancel-hover](https://cloud.githubusercontent.com/assets/16934586/17098191/b8903c44-527e-11e6-81a6-a3d8f84118a0.png)

**Comment by scottwhitsitt** [comment]
This is done and already included in 7.5
