### ISSUE TITLE
Make articles change URL in the browser to allow for direct linking to Topic and Article

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#16]

**Comment by sdubrick** [comment]
It now shows the article and topic ID in the URL.  However, this method is not good as it does a complete page refresh on every article or topic click instead of loading the article asynchronously like it did before.  

Most likely we cannot have both the article showing as a direct link URL in the browser chrome AND have it use AJAX properly.  So, instead, please use the previous ajax method, but provide a way to copy and paste a direct link from the article. A nice method of accomplishing this is to do similar to what StackOverflow does.  When the 'share' link is clicked, a modal comes up with the direct link inside:
![image](https://cloud.githubusercontent.com/assets/5289502/12825642/fc64b040-cb3c-11e5-8bdb-79c36eae40d2.png)

**Comment by sdubrick** [comment]
Seems good:
![image](https://cloud.githubusercontent.com/assets/5289502/12938366/5597a666-cfe5-11e5-854a-633f6ab68ac6.png)

**Comment by sdubrick** [comment]
Per scotts comment in another issue:
![image](https://cloud.githubusercontent.com/assets/5289502/12938869/b5440b58-cfeb-11e5-9387-1062aec4a682.png)

**Comment by jaswantchouhan** [comment]
Done- converted in button
