### ISSUE TITLE
Use rating for Top 5 Article list

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#17]
Use the rating parameter to sort the top 5 FAQs.

**Comment by sdubrick** [comment]
Doesn't appear to be working.  Top rated articles aren't listed in the top 5:
![image](https://cloud.githubusercontent.com/assets/5289502/12938759/3ff9a1a6-cfea-11e5-8ebb-457bc3b3323a.png)

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
Looks ok, but please do a code commit to github. We can discuss on call how to do

**Comment by sdubrick** [comment]
test, ignore

**Comment by sdubrick** [comment]
test - ignore this comment
