### ISSUE TITLE
Issues with responsive layout for login panel

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#22]
The login panel is not expanding properly. Below is the view on a Note 3 ...

![2016-02-03](https://cloud.githubusercontent.com/assets/16782471/12787666/0390c890-ca5c-11e5-9d51-bac2ace68012.png)

Below is how the login panel should look.

![2016-02-03 1](https://cloud.githubusercontent.com/assets/16782471/12787651/f7fbcef8-ca5b-11e5-8cc7-6f2ea63954f5.png)

**Comment by ashrafsabrym** [comment]
I can't see a problem in the above image except that the tip of the login box is not aligned with the login link.

**Comment by scottwhitsitt** [comment]
Try to login on your phone and you will see the issue.

**Comment by ashrafsabrym** [comment]
Fixed in PR #29 
Please confirm that it's fixed

**Comment by sdubrick** [comment]
Scott, please confirm this one.. don't have a Note to confirm it myself

**Comment by scottwhitsitt** [comment]
Formatting properly on Note3 now.
