### ISSUE TITLE
Responsive view of form is not properly expanded

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#24]
Below is a screenshot on a Note3. The text is not properly sizing for the viewport.

![2016-02-03 2](https://cloud.githubusercontent.com/assets/16782471/12787971/3eec4a62-ca5d-11e5-9016-bdd6e4814e7c.png)

**Comment by ashrafsabrym** [comment]
Do you mean that the columns shouldn't be stacked at this width?
Foundation has a breakpoint at 1024 pixels. Widths less than this causes the stacked style to be applied.
Should I change this behaviour?

**Comment by sdubrick** [comment]
duplicate issue #22
