### ISSUE TITLE
Missing sort indicator and text display issue

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#25]
As shown below, the sort indicator is missing on the Oldest message column, The message date column heading is white on white.

![2016-02-03_10-46-57](https://cloud.githubusercontent.com/assets/16782471/12789540/e5f73424-ca63-11e5-8a4c-43ad3a658dff.png)

**Comment by ashrafsabrym** [comment]
Fixed. But I had to change the background colour of table header to dark grey (like this of form 68) so that the white sort indicators appear.

**Comment by scottwhitsitt** [comment]
If you're going to use a dark background, you need to change the font color. Blue on black is not readable.
![2016-02-11_19-28-55](https://cloud.githubusercontent.com/assets/16782471/12996475/d891047a-d0f5-11e5-83fe-5514a8c3a1de.png)

**Comment by sdubrick** [comment]
I would suggest just keeping it simple, keep it purple on gray, but don't have it change color to white during sort. There is already a sort indicator icon, so not necessary to change color too.

**Comment by sdubrick** [comment]
I would suggest just keeping it simple, keep it purple on gray, but don't have it change color to white during sort. There is already a sort indicator icon, so not necessary to change color too.

**Comment by ashrafsabrym** [comment]
Ok. I changed text colour to white
