### ISSUE TITLE
Issue with footer on page resize

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#26]
When the form is reduced in width, the footer text overlaps.

![2016-02-04_9-16-45](https://cloud.githubusercontent.com/assets/16782471/12820971/0755f858-cb27-11e5-9f9b-611f1745c60b.png)

**Comment by ashrafsabrym** [comment]
I can't fix this part. It's included by an `$include` directive.
It's near the bottom of the form markup:
`$include -placeholder'common-footer' -indent'  '$`

**Comment by sdubrick** [comment]
You should be able to break out a version of that footer into a new form id that has responsive changes, then include that form instead.  The default footer placeholder code itself is fairly simple, and can be found here:
https://qa.iservicecrm.com/f/diag-builtinforms?main=body&formID=ngappbuiltin-common-footer

**Comment by ashrafsabrym** [comment]
Fixed by giving the copyright div a bottom padding so that the anti-spam policy link rests in the
padding area on narrow screens.

**Comment by sdubrick** [comment]
@seani @swhitsit we might want put ashrafs padding changes into the builtin footer to accommodate responsive pages better

example:
![image](https://cloud.githubusercontent.com/assets/5289502/13040257/66916fbe-d36f-11e5-8367-08d2607cf474.png)

**Comment by scottwhitsitt** [comment]
That sounds like a good idea. The HTML is simple and seems unlikely to have any conflicts in the core pages.
