### ISSUE TITLE
Responsive navigation not working for 1to1 header

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#27]
The header code that includes the Corp navigation displays properly on mobile, but the links to not redirect to the corp 1to1service.com website.

**Comment by sdubrick** [comment]
The 1to1 header/footer are not responsive - see how the 1to1service.com site becomes responsive (nav changes to dropdown):
![image](https://cloud.githubusercontent.com/assets/5289502/12939006/49ae6242-cfed-11e5-92bf-58ee1b6964a9.png)

The form though doesn't follow this: (tested in form 21 sandbox):
![image](https://cloud.githubusercontent.com/assets/5289502/12939026/748a1236-cfed-11e5-9e68-2d278622b36e.png)

**Comment by scottwhitsitt** [comment]
Works on Note3
