### ISSUE TITLE
Deleted duplicate form code

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#3]
The customer portal - tree form includes duplicate code that needs to be removed to avoid the form size limit.

**Comment by sdubrick** [comment]
removed by adam. jc still needs to checkin the updated code though from form 92

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
need to see checkin to close

**Comment by sdubrick** [comment]
i'm going to just close this for now to get it out of the way.  Will set up a time i can guide JC on the checkin/pull request process
