### ISSUE TITLE
Round minutes on mobile display

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#30]
On iPhone and Note3 the minutes are displaying a large number of decimal places.

![2016-02-05](https://cloud.githubusercontent.com/assets/16782471/12857076/c4a20e6a-cc0d-11e5-9efb-9fba7a87046c.png)

**Comment by ashrafsabrym** [comment]
Fixed in #32

**Comment by scottwhitsitt** [comment]
Works properly on Note3 now.
