### ISSUE TITLE
Correct date format

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#34]
The date is now displayed as 2015-12-05T08:34:32.3670000Z because of a change to ISO format.

**Comment by sdubrick** [comment]
iService now uses moment.js to handle iso dates. Example of usage is:

{{article.date|amDateFormat:'YYYY-MM-DD h:mm:ss A'}}

You can see this example in form 92, which is an included part of form 21

**Comment by ashrafsabrym** [comment]
I get an error when I apply it, and can't debug the minified code to know the reason.
Is this filter applied elsewhere?

**Comment by ashrafsabrym** [comment]
Per your instructions on hangout, I fixed the issue.
