### ISSUE TITLE
Use responsive table

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#35]
Retain the current example, but provide an example that uses a responsive table keeping the columns for smaller screens.

For the stacking version, make the Agent Name bold.

**Comment by ashrafsabrym** [comment]
I applied the responsive tables plugin to form 94. It doesn't work and caused the agent messages tables to stop working too.

**Comment by sdubrick** [comment]
@swhitsit are you ok with the accordian style instead? i'll wait to close this until i hear from you on it - for me it's ok

**Comment by scottwhitsitt** [comment]
I'm ok with the stacked view for now. We can consider a round of enhancements after 7.4 is released.
