### ISSUE TITLE
Correct date format

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#36]
Update all dates to use the new moment.js ISO format.  An example is below, but there may be more that need to be fixed

![image](https://cloud.githubusercontent.com/assets/5289502/12938212/3035f456-cfe3-11e5-9666-b74aff3f157b.png)

**Comment by sdubrick** [comment]
Another instance is in My Inbox
![image](https://cloud.githubusercontent.com/assets/5289502/12943776/134a9c38-d016-11e5-8205-6509bdbd2310.png)

**Comment by jaswantchouhan** [comment]
done
