### ISSUE TITLE
Page load dimmer isn't active on entire page

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#37]
See screenshot.  If the page is scrolled down past the initial view, then an article is selected, the page load dimmer isn't active across the entire page.  The active view should dim, and the circular spinner should always spin on what is the center of the active view on the page

![image](https://cloud.githubusercontent.com/assets/5289502/12938263/ea8b6d40-cfe3-11e5-8549-a5fa93c22fe0.png)

**Comment by jaswantchouhan** [comment]
done
