### ISSUE TITLE
Form doesn't function if user is not in CST time zone

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#40]
See error from console below.  Might be related to the ISO changes that adam made (issue #34)  It looks like the work hour calculator is outputting the server's time (CST), but then falsely labelling it as the user's local time.  In this error below, the 'real' server date time should have been Wed Feb 10 2016 17:15:53 GMT+0700.  It is incorrectly giving the time as 04:15:53 (which is CST) and labeling it as my local time in SE Asia.  When the error occurs, no rows are displayed:
![image](https://cloud.githubusercontent.com/assets/5289502/12944708/71f42ca4-d01b-11e5-88d6-2ca00fcf9243.png)

```
17:17:59.460 Error: The provided date (Wed Feb 10 2016 17:12:50 GMT+0700 (SE Asia Standard Time)) is past the server date (Wed Feb 10 2016 04:15:53 GMT+0700 (SE Asia Standard Time))
calculateWorkHours@https://qa.iservicecrm.com/f/84:68:1
onDataFetched/<@https://qa.iservicecrm.com/f/79?form=js:46:23
onDataFetched@https://qa.iservicecrm.com/f/79?form=js:44:5
ServicePost/us.promise<@https://qa.iservicecrm.com/js/iService.util.js?v=7.4+-+2016.02.09+-+05%3a36%3a00:686:9
r/f.success/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:72:216
Be/e/l.promise.then/J@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:100:415
Be/e/l.promise.then/J@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:100:415
Be/g/<.then/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:102:64
Zd/this.$get</k.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:112:315
Zd/this.$get</k.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:109:384
Zd/this.$get</k.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:113:98
h@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:72:469
w@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:77:395
xe/</z.onreadystatechange@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js:78:475
1 angular.min.js:92:210
e/<() angular.min.js:92
Rd/this.$get</<() angular.min.js:68
Be/e/l.promise.then/J() angular.min.js:100
Be/e/l.promise.then/J() angular.min.js:100
Be/g/<.then/<() angular.min.js:102
Zd/this.$get</k.prototype.$eval() angular.min.js:112
Zd/this.$get</k.prototype.$digest() angular.min.js:109
Zd/this.$get</k.prototype.$apply() angular.min.js:113
h() angular.min.js:72
w() angular.min.js:77
xe/</z.onreadystatechange() angular.min.js:78

```

**Comment by ashrafsabrym** [comment]
This issue is caused by that the server time in the calculation code emitted by $value -now$ is still not in the ISO format, and it's parsed as client local time.
While the time in the interaction objects is now in the ISO format and preserves server time zone.

This mismatch causes the error. It causes that as if the interaction has future time.

**Comment by sdubrick** [comment]
From my understanding, the now value needs to be changed on the iService side, so this would be for Adam.  Adam, would this have major consequences elsewhere? (Are there many areas that use the now value and would need to be updated?)

**Comment by ashrafsabrym** [comment]
It's apparent that this function is used to display date and time for users, so, modifying it to output in the ISO format may affect other screens.
It's better to create a new one.

**Comment by sdubrick** [comment]
From adam:

> "I'm going to have it look for the -Pjs flag which can be used with the other $value$ variables, and output ISO format if it finds it."

**Comment by sdubrick** [comment]
@ashrafsabrym 
From adam:

> use -isoutc flag in any date value to make it output in ISO standard format.
