### ISSUE TITLE
Reduce contact details field padding

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#42]
From joe:
1.  Padding in Contact Details is too much making the page unnecessarily taller
![image](https://cloud.githubusercontent.com/assets/5289502/12973209/4e6f5318-d0dd-11e5-9685-a6c0f8458b5d.png)

**Comment by jaswantchouhan** [comment]
Done
![iservice crm 2016-02-14 12-43-26](https://cloud.githubusercontent.com/assets/16934586/13032432/976547a2-d318-11e5-8ec9-7c1641db9b52.png)

**Comment by sdubrick** [comment]
Reduce padding even more
Also, please increase the fields to use all 3 columns

**Comment by jaswantchouhan** [comment]
changed the form in four columns

**Comment by sdubrick** [comment]
looks much nicer
