### ISSUE TITLE
Add modal alert after note has been submitted

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#43]
(Per joe) Our unofficial style guide is to avoid modals in forms, but this form is not intended to be responsive.  So, please add it in this case.  It should of course disappear after a second:
![image](https://cloud.githubusercontent.com/assets/5289502/12973315/062fa584-d0de-11e5-992a-36621e38ea5c.png)

**Comment by jaswantchouhan** [comment]
how i have done this for responsive too, in which case this message box (Add modal alert ) appears

**Comment by sdubrick** [comment]
still needs a notification. jc can determine how to implement this and how it looks.

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
looks great
