### ISSUE TITLE
Upper contact box changes

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#44]
per joe: 3. Remove italics from “Contact” box and remove duplicate first, m.i., last name fields

![image](https://cloud.githubusercontent.com/assets/5289502/12973414/cad5122a-d0de-11e5-9789-ecd2c81d6f83.png)

**Comment by jaswantchouhan** [comment]
removed italic not clear the second poing

**Comment by jaswantchouhan** [comment]
done
