### ISSUE TITLE
From: address in ticket/agent email should have dropdown value

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#45]
per joe:
4.  In Contact Historyany interactionAgent email or Create Ticket: the From: and To: fields, there are no options showing to select an email address

![image](https://cloud.githubusercontent.com/assets/5289502/12973469/205c0596-d0df-11e5-8534-fd1949219650.png)

![image](https://cloud.githubusercontent.com/assets/5289502/12973484/3d51b2b8-d0df-11e5-893b-9d040d7c88eb.png)

**Comment by jaswantchouhan** [comment]
Done
in my case is create ticket from email is selected shown in screen shot
![iservice crm 2016-02-14 12-38-18](https://cloud.githubusercontent.com/assets/16934586/13032422/f5521472-d317-11e5-9632-b2cd3d8dc5e5.png)

in case of agent email getting the "To" filed filled screen shot attached
![iservice crm 2016-02-14 12-42-00](https://cloud.githubusercontent.com/assets/16934586/13032429/635a2a4a-d318-11e5-8998-d532e6237c3a.png)

**Comment by sdubrick** [comment]
Works on contact id 51 and others, but does not work on contact id 2

Possibly a backend bug @seani

**Comment by sdubrick** [comment]
I believe that this only happens if you are browsing your own history or the agent doesn't have an email address as a login name.  Going to close this, since that wouldn't be an issue
