### ISSUE TITLE
Private Note and Public Note buttons should be in one row

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#46]
Per joe:
![image](https://cloud.githubusercontent.com/assets/5289502/12973500/5707c652-d0df-11e5-8571-37be25c4bd96.png)

**Comment by jaswantchouhan** [comment]
done 
![iservice crm 2016-02-14 12-02-44](https://cloud.githubusercontent.com/assets/16934586/13032313/f1729340-d312-11e5-8886-3db930fd5472.png)
