### ISSUE TITLE
Incorporate CSS into form

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#49]
Rather than including form 68, incorporate the required CSS directly into the Assigned Messages form.

**Comment by ashrafsabrym** [comment]
Done.
And found out that form 68 wasn't having any CSS, but including forms 83, 85 and 82.
I placed this huge amount of CSS in the form for now, but should be revised later because the relevant part for the form is only the login panel part.

**Comment by swhitsit** [comment]
The CSS will be removed and embedded directly into those forms, so we suggest you do the same. The form needs to be portable without any hard coded $includes.
