### ISSUE TITLE
Correct login panel

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#5]
The login panel is not properly sized

**Comment by ashrafsabrym** [comment]
May you specify the problem with panel size? Do you mean that it has large padding amount?

The styles controlling this panel are in a form not currently in the repository. They're in form 53 on the QA tenant.

**Comment by sdubrick** [comment]
The login panel should use updated code from form 68.  This won't 'fix' the login panel size, but it will fix some other bugs in it like client side email validation of logins

**Comment by ashrafsabrym** [comment]
Fixed in pull request #11

**Comment by sdubrick** [comment]
Appears fixed
