### ISSUE TITLE
Remove follow-up date and close reason portions

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#59]
Remove the highlighted sections. You will also need to remove the error checking that these properties exist
![image](https://cloud.githubusercontent.com/assets/5289502/13106982/d35d9836-d59d-11e5-8d18-0e4f4d7b4c37.png)

**Comment by scottwhitsitt** [comment]
We also need to remove "Time Zone" and "Next Action" from the Contact section. Also, please rename the "Contact" section "Contact Info" because it is not just the contact's name.

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
Please change from "Contact Info" to "Contact Summary"

**Comment by sdubrick** [comment]
The validation of various contact properties needs to be removed so that the form is generic across tenants

**Comment by jaswantchouhan** [comment]
done
