### ISSUE TITLE
Incorrect method of referencing placeholder

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#61]
https://github.com/OneToOneService/iService-Forms/blob/master/Assigned-Messages/MainBody.frm#L1505

This line uses a direct reference to a /f/ form name placeholder, but this is the wrong method of referencing iservice forms since it doesn't allow the form to be portable when it's converted to a builtin version (which don't have /f/ in the name).  Change to use something like:
`<script> $include -placeholder'assigned-msg-hours'$ </script>`

**Comment by seani** [comment]
The way it's used with /f/ works correctly, and I would say is preferred in this situation.
