### ISSUE TITLE
Password Reset Link doesn't email a valid reset link

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#64]
Per adam, please make this change to the javascript:

`confirm=$value`
changes to
`confirm=$'+'value`

**Comment by jaswantchouhan** [comment]
code is same

**Comment by jaswantchouhan** [comment]
password reset is also not working in provided base code
https://qa.iservicecrm.com/f/93

**Comment by jaswantchouhan** [comment]
done
