### ISSUE TITLE
CSS/JS specific only to the StandardHeader and StandardFooter need to be moved there

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#70]
- [x] Any CSS/JS that is specific only to the StandardHeader and StandardFooter should be moved into those forms, not included as part of the treeview forms.  For other tenants, they will have have either a different (or no) standard header/footer, which means that this CSS code is just taking up space in the treeview forms.

Also, after that:
- [x] move the contents of StandardHeader.frm to a new file called 
- [x] CustomerPortal/1to1header.frm
- [x] move the contents of StandardFooter.frm to a new file called CustomerPortal/1to1footer.frm
- [x] StandardHeader.frm and StandardFooter.frm should then be empty
- [x] Rename StandardHeader.frm to customerportal-standard-header.frm and move to CustomerPortal/ folder
- [x] Rename StandardFooter.frm to customerportal-standard-footer.frm and move to CustomerPortal/ folder

**Comment by sdubrick** [comment]
The main part isn't done - the specific css for the 1to1header/1to1footer needs to be moved from previewdialer-css to reside in those forms

**Comment by sdubrick** [comment]
To clarify - you did copy that css to 1to1header, which is correct, but it then also needs to be removed from treeview-css

**Comment by jaswantchouhan** [comment]
removed form the tree view css
