### ISSUE TITLE
My Inbox history displays agent-only actions for regular users

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#76]
This is an issue with the generic sample for also.  These should not be shown to the customer, since they don't have the privileges.  Since this is a customer portal, it might be ok to just hide them in all cases, even for agents:

![image](https://cloud.githubusercontent.com/assets/5289502/13151737/179d4a68-d69e-11e5-9c8a-1bb4d0f4d33d.png)

**Comment by jaswantchouhan** [comment]
i need to just removed the html or need to do anything else i just used it
as it was in base

**Comment by sdubrick** [comment]
If you can simply hide these for now, that's probably good enough for now - it's not a security issue because the server side does permission checking before actually accepting the actions performed.  The real solution is to have the correct actions display depending on the permission level of the user, but that requires a change in the base functions for displaying history items

**Comment by sdubrick** [comment]
JC - any progress on this?

**Comment by jaswantchouhan** [comment]
i have done this on last saturday also commited on git hub

**Comment by sdubrick** [comment]
I see that the commit is there now.. probably good to comment on the issue when it's done, otherwise we might not notice

**Comment by jaswantchouhan** [comment]
yes
