### ISSUE TITLE
Elements flash by before page renders completely

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#77]
I noticed today that the elements in the preview dialer briefly display before the page has finished loading - so for example, when loading the for the first time before logged in, it will show the elements (like the screenshot below), and then they disappear and the login panel appears.  These should only appear after logging in.  Probably you will need to use ng-cloak directives or something - you can see how they're used in other forms

![image](https://cloud.githubusercontent.com/assets/5289502/13169106/92cd9dd8-d715-11e5-8444-2063ba7e325c.png)

**Comment by jaswantchouhan** [comment]
done
