### ISSUE TITLE
Update forms to match guidelines

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#88]
This applies to treeview and preview dialer:

Make all indentation 2 spaces.
Only use double quotes where absolutely necessary (such as in HTML elements).
Because we don't minimize, remove comments.
Remove all unused CSS.
Format CSS like the static iService CSS files, with each directive on a single line.

**Comment by scottwhitsitt** [comment]
The builtin version is updated, and future updates will be made to that form.
