### ISSUE TITLE
Fix verbiage and hyperlink for anonymous user

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#98]
The following message is shown in the My Inbox page to anon users.

"Required Login to view your details. If you don’t have an account in our support portal Sign Up now "

Instead, the message should be as follows:

"Please login to view your message history. If you don;t have an account you can Sign Up now."

The words Sign Up need to be a hyperlink to the Sign Up panel.

**Comment by jaswantchouhan** [comment]
fixed

**Comment by scottwhitsitt** [comment]
There is a typo in the word don't. You are using a semi-colon.

![2016-05-11_15-58-28](https://cloud.githubusercontent.com/assets/16782471/15196364/789b5bb4-1791-11e6-8ba5-c62fc6aedff2.jpg)

**Comment by jaswantchouhan** [comment]
typo in the statement fixed issue #98

**Comment by scottwhitsitt** [comment]
Tested this on f/112 and it appears to be corrected
