### ISSUE TITLE
Update angular-ui-bootstrap to latest, move custom edits out of the standard library

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#99]
The current angular-ui-bootstrap used in treeview is very old - update to latest, and move the custom changes to it out into the main form (instead of editing the library itself)

**Comment by jaswantchouhan** [comment]
#issue #99 -  angular-ui-bootstrap is updated for tree view please verify on http://outdev2.1to1vpn.ddns.net:9015/f/58#/find-answers now using https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/1.3.2/ui-bootstrap-tpls.js

**Comment by sdubrick** [comment]
Confirmed fixed at http://outdev2.1to1vpn.ddns.net:9015/f/58#/find-answers
